### ISSUE TITLE
Unable to run IP-Adapter in ComfyUI on Mac/Apple Silicon/MPS

### ISSUE THREAD

**Issue by leobridle** [tencent-ailab/IP-Adapter#95]
Whenever I use IP-Adapter in a ComfyUI workflow, I get the following error:

`Error occurred when executing IPAdapter:  Torch not compiled with CUDA enabled  File "/Users/username/ComfyUI/execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/username/ComfyUI/execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/username/ComfyUI/execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/username/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 171, in adapter self.ipadapter.to(device, dtype=self.dtype) File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to return self._apply(convert) ^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply module._apply(fn) File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply module._apply(fn) File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply param_applied = fn(param) ^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") 
`

I think this is a similar issue to the one discussed here for Automatic1111 https://github.com/tencent-ailab/IP-Adapter/issues/53

I would appreciate any help here to apply a similar fix!

**Comment by xiaohu2015** [comment]
@leobridle do you try this https://github.com/tencent-ailab/IP-Adapter/issues/53#issuecomment-1729322454

**Comment by leobridle** [comment]
@xiaohu2015 Thanks, but Comfy UI doesn't seem to use the same files as Automatic1111.
I cannot find a file like extensions/sd-webui-controlnet/annotator/clipvision/init.py

**Comment by leobridle** [comment]
Ah nevermind! I found the fix here https://github.com/laksjdjf/IPAdapter-ComfyUI/issues/26#issuecomment-1736845902

> The workaround is to change "device" at line 142 of ip_adapter.py to
device = "mps" (or I guess "cpu"). Then restart comfyui and it works. Make sure the dtype is set to fp32 in the LoadIPAdaptor node too!

**Comment by pphoto808** [comment]
I have just the opposite. IP-Adapter works fine on my Studio M2 Ultra but NOT in Automatic1111
